const request = require('supertest')
const { setupIntegrationTest, teardownIntegrationTest, getApp, createVerifiedUser, bearerToken } = require('../helpers/test-harness')
const Votation = require('../../models/Votation')
const VotingElectorateBase = require('../../models/VotingElectorateBase')
const VotingElector = require('../../models/VotingElector')
const VotingCategory = require('../../models/VotingCategory')
const VotingCandidate = require('../../models/VotingCandidate')
const { tallyElection } = require('../../helpers/voting-election-service')

describe('votação — bases eleitorais por pleito', () => {
  beforeAll(() => setupIntegrationTest())
  afterAll(() => teardownIntegrationTest())

  test('importa base, vincula ao pleito e restringe elegibilidade', async () => {
    const admin = await createVerifiedUser({ email: 'base-admin@test.local', role: 'admin-votacao' })
    const token = bearerToken(admin)
    const imported = await request(getApp())
      .post('/votacao/admin/electorate-bases/import')
      .set('Authorization', `Bearer ${token}`)
      .send({ name: 'Conselho Municipal 2026', csv: 'Nome;CPF;Identificador;Entidade\nMaria Teste;52998224725;CON-01;Conselho' })
    expect(imported.status).toBe(201)
    expect(imported.body.imported).toBe(1)

    const now = Date.now()
    const create = await request(getApp())
      .post('/votacao/admin/votacoes')
      .set('Authorization', `Bearer ${token}`)
      .send({ title: 'Eleição Conselho', startDate: new Date(now - 1000), endDate: new Date(now + 86400000), status: 'active', electorateBaseId: imported.body.base.id })
    expect(create.status).toBe(201)
    expect(String(create.body.votation.electorateBaseId)).toBe(imported.body.base.id)

    const slug = create.body.votation.slug
    const ok = await request(getApp()).post(`/votacao/pleitos/${slug}/unlock`).send({ cpf: '52998224725' })
    expect(ok.status).toBe(200)
    const cat = await VotingCategory.create({ votationId: create.body.votation._id, name: 'Representante' })
    const candidate = await VotingCandidate.create({ votationId: create.body.votation._id, categoryId: cat._id, number: 1, name: 'Pessoa Candidata' })
    const ballot = await request(getApp()).get(`/votacao/votacoes/${create.body.votation._id}/ballot`).set('Authorization', `Bearer ${ok.body.accessToken}`)
    expect(ballot.status).toBe(200)
    const vote = await request(getApp()).post(`/votacao/votacoes/${create.body.votation._id}/ballot`).set('Authorization', `Bearer ${ok.body.accessToken}`).send({ choices: [{ categoryId: String(cat._id), voteType: 'candidate', candidateId: String(candidate._id) }] })
    expect(vote.status).toBe(201)
    const denied = await request(getApp()).post(`/votacao/pleitos/${slug}/unlock`).send({ cpf: '39053344705' })
    expect(denied.status).toBe(401)
  })

  test('não troca base depois que o pleito sai de rascunho', async () => {
    const admin = await createVerifiedUser({ email: 'base-lock@test.local', role: 'admin-votacao' })
    const token = bearerToken(admin)
    const vot = await Votation.create({ title: 'Já ativo', startDate: new Date(), endDate: new Date(Date.now() + 86400000), status: 'active' })
    const base = await VotingElectorateBase.create({ name: 'Base bloqueada', type: 'imported' })
    const res = await request(getApp()).patch(`/votacao/admin/votacoes/${vot._id}/electorate-base`).set('Authorization', `Bearer ${token}`).send({ electorateBaseId: base._id })
    expect(res.status).toBe(422)
  })

  test('admin lista, adiciona, edita e exclui eleitor de base importada', async () => {
    const admin = await createVerifiedUser({ email: 'base-crud@test.local', role: 'admin-votacao' })
    const token = bearerToken(admin)
    const base = await VotingElectorateBase.create({ name: 'Base CRUD', type: 'imported' })

    const created = await request(getApp())
      .post(`/votacao/admin/electorate-bases/${base._id}/electors`)
      .set('Authorization', `Bearer ${token}`)
      .send({ name: 'João da Silva', identifier: 'MAT-100', cpf: '52998224725', group: 'SAAE' })
    expect(created.status).toBe(201)
    expect(created.body.elector.cpfLast4).toBe('4725')
    expect(created.body.elector.cpfHash).toBeUndefined()

    const listed = await request(getApp())
      .get(`/votacao/admin/electorate-bases/${base._id}/electors?search=joao`)
      .set('Authorization', `Bearer ${token}`)
    expect(listed.status).toBe(200)
    expect(listed.body.electors).toHaveLength(1)

    const updated = await request(getApp())
      .patch(`/votacao/admin/electorate-bases/${base._id}/electors/${created.body.elector.id}`)
      .set('Authorization', `Bearer ${token}`)
      .send({ name: 'João da Silva Atualizado', identifier: 'MAT-101', cpf: '', role: 'Analista' })
    expect(updated.status).toBe(200)
    expect(updated.body.elector.identifier).toBe('MAT-101')

    const removed = await request(getApp())
      .delete(`/votacao/admin/electorate-bases/${base._id}/electors/${created.body.elector.id}`)
      .set('Authorization', `Bearer ${token}`)
    expect(removed.status).toBe(200)
    expect(await VotingElector.countDocuments({ _id: created.body.elector.id, active: { $ne: false } })).toBe(0)
  })

  test('apuração conta aptos da base vinculada, não da base global', async () => {
    const base = await VotingElectorateBase.create({ name: 'Base restrita', type: 'imported' })
    await VotingElector.create({ electorateBaseId: base._id, identifier: 'R-1', cpfHash: 'cpf-r1', cpfLast4: '0001', identityHash: 'id-r1', name: 'Eleitor Restrito' })
    const vot = await Votation.create({ title: 'Pleito restrito', startDate: new Date(), endDate: new Date(Date.now() + 86400000), status: 'test', electorateBaseId: base._id })
    const result = await tallyElection(vot._id)
    expect(result.eligibleVoters).toBe(1)
  })
})
