const {TYPES}=require('../models/ComturContent');const TYPE_SET=new Set(TYPES);const STATUSES=new Set(['draft','review','published','archived']);const TRANS={draft:new Set(['review','published','archived']),review:new Set(['draft','published','archived']),published:new Set(['review','archived']),archived:new Set(['draft'])};const txt=(v,n)=>typeof v==='string'?v.trim().slice(0,n):''
function url(v){const s=txt(v,1000);if(!s)return'';if(/^\/[a-z0-9/_\-.]+$/i.test(s))return s;try{const u=new URL(s);return['http:','https:'].includes(u.protocol)?s:null}catch(_){return null}}
function normalize(input={},partial=false){const out={};if(!partial)for(const k of ['type','slug','title'])if(!input[k])return{error:`Campo obrigatório: ${k}`};if(input.type!==undefined){if(!TYPE_SET.has(input.type))return{error:'Tipo de conteúdo inválido'};out.type=input.type}if(input.slug!==undefined){const s=txt(input.slug,180).toLowerCase();if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(s))return{error:'Slug inválido'};out.slug=s}for(const[k,n]of[['title',240],['summary',2000],['body',50000],['location',300]])if(input[k]!==undefined){out[k]=txt(input[k],n);if(k==='title'&&!out[k])return{error:'Título obrigatório'}}for(const k of ['startsAt','endsAt'])if(input[k]!==undefined){if(!input[k])out[k]=null;else{const d=new Date(input[k]);if(Number.isNaN(d.getTime()))return{error:`Data inválida: ${k}`};out[k]=d}}if(input.featured!==undefined)out.featured=input.featured===true;if(input.geo!==undefined){const lat=Number(input.geo.lat),lng=Number(input.geo.lng);if(!Number.isFinite(lat)||lat< -90||lat>90||!Number.isFinite(lng)||lng< -180||lng>180)return{error:'Coordenadas inválidas'};out.geo={lat,lng}}if(input.contact!==undefined){for(const k of ['website'])if(input.contact[k]&&url(input.contact[k])===null)return{error:'URL de contato inválida'};out.contact={phone:txt(input.contact.phone,60),email:txt(input.contact.email,180),website:url(input.contact.website)}}if(input.media!==undefined){if(!Array.isArray(input.media))return{error:'Mídias devem ser uma lista'};out.media=[];for(const m of input.media){const u=url(m.url);if(!['image','video','audio','document','link'].includes(m.kind)||!u)return{error:'Mídia inválida'};out.media.push({kind:m.kind,title:txt(m.title,180),url:u,mimeType:txt(m.mimeType,120),isAccessible:m.isAccessible===true})}}if(input.metadata!==undefined)out.metadata=input.metadata&&typeof input.metadata==='object'?input.metadata:{};if(input.translations!==undefined)out.translations=input.translations&&typeof input.translations==='object'?input.translations:{};return{value:out}}
const canTransition=(a,b)=>STATUSES.has(a)&&STATUSES.has(b)&&TRANS[a].has(b)
function publicContentFilter(query={}){
  const filter={status:'published'}
  if(query.type){if(!TYPE_SET.has(String(query.type)))return{error:'Tipo inválido'};filter.type=String(query.type)}
  if(query.featured==='true'||query.featured==='1')filter.featured=true
  const q=typeof query.q==='string'?query.q.trim().slice(0,120):''
  if(q)filter.$text={$search:q}
  return{filter}
}
module.exports={normalize,canTransition,TYPE_SET,publicContentFilter}
