const multer=require('multer');const path=require('path');const fs=require('fs');const crypto=require('crypto');const{execFile}=require('child_process');const{BASE_DIR}=require('./image-upload');const DIR=path.join(BASE_DIR,'comtur');const MAX=25*1024*1024;const allowed=new Set(['application/pdf','image/jpeg','image/jpg','image/png','image/webp','image/x-icon','image/vnd.microsoft.icon','audio/mpeg','video/mp4'])
const IMAGE_EXT=new Set(['.jpg','.jpeg','.png','.webp','.ico','.pdf','.mp3','.mp4'])
function mimeOf(file){const mime=String(file?.mimetype||'').toLowerCase();return mime==='image/jpg'?'image/jpeg':mime}
const storage=multer.diskStorage({destination(_r,_f,cb){try{fs.mkdirSync(DIR,{recursive:true});cb(null,DIR)}catch(e){const err=new Error('Pasta de imagens do portal indisponível.');err.status=500;cb(err)}},filename(_r,f,cb){cb(null,`${Date.now()}-${crypto.randomBytes(10).toString('hex')}${path.extname(f.originalname||'').toLowerCase()}`)}})
const upload=multer({storage,limits:{fileSize:MAX},fileFilter(_r,f,cb){const mime=mimeOf(f);const ext=path.extname(f.originalname||'').toLowerCase();allowed.has(mime)||IMAGE_EXT.has(ext)?cb(null,true):cb(new Error('Use JPEG, PNG ou WebP para o banner.'))}}).single('file')
function magicOk(file){const b=fs.readFileSync(file.path).subarray(0,12);const m=mimeOf(file);return m==='application/pdf'?b.subarray(0,5).toString()==='%PDF-':m==='image/png'?b.subarray(1,4).toString()==='PNG':m==='image/jpeg'?b[0]===0xff&&b[1]===0xd8:m==='image/webp'?b.subarray(0,4).toString()==='RIFF'&&b.subarray(8,12).toString()==='WEBP':m.includes('icon')?b[0]===0&&b[1]===0&&b[2]===1&&b[3]===0:true}
function scan(file){return new Promise((resolve,reject)=>execFile(process.env.CLAMSCAN_BIN||'clamscan',['--no-summary',file],{timeout:120000},(e,stdout)=>{if(!e)return resolve();const err=new Error(e.code==='ENOENT'?'Antivírus institucional indisponível':'Arquivo reprovado pelo antivírus');err.status=e.code==='ENOENT'?503:422;err.details=String(stdout||'').slice(0,300);reject(err)}))}
async function validateAndScan(file){if(!magicOk(file)){const e=new Error('Conteúdo do arquivo não corresponde ao formato declarado');e.status=422;throw e}await scan(file.path);const hash=crypto.createHash('sha256').update(fs.readFileSync(file.path)).digest('hex');return{url:`/images/comtur/${file.filename}`,hash,mimeType:file.mimetype,sizeBytes:file.size,originalName:file.originalname}}
module.exports={upload,validateAndScan,MAX}
